#!/bin/bash

# Test 03: Test the http-proxy with a binary file GET request and response

# Start timer for test
echo "+ ------- Test 03: Binary File GET request and response ------- +"

echo "[*] Sending initial request to http://www.cs.cmu.edu/~dga/dga-headshot.jpg..."
fetch=$(/usr/bin/time -f "%e" curl -v --output headshot.jpg -x localhost:9056 http://www.cs.cmu.edu/~dga/dga-headshot.jpg 2>&1)

echo "[*] Sleeping for 5 seconds..."
for i in {1..5}; do
    echo -n "."
    sleep 1
done
echo ""

echo "[*] Sending second request to http://www.cs.cmu.edu/~dga/dga-headshot.jpg..."
cache=$(/usr/bin/time -f "%e" curl -v --output headshot.jpg -x localhost:9056 http://www.cs.cmu.edu/~dga/dga-headshot.jpg 2>&1)

echo "[+] Results ----------------------------------------------- +"
echo ""
echo "    [*] Time Elapsed w/ Fetch: $fetch"
echo "    [*] Time Elapsed w/ Cache: $cache"
echo ""
echo "+ --------------------------------------------------------- +"
