#!/bin/bash

# Test 02: Test the http-proxy with a simple GET request and response

# Start timer for test
echo "+ ---------- Test 02: Simple GET request and response --------- +"

echo "[*] Sending initial request to http://www.cs.cmu.edu/~prs/bio.html..."
fetch=$(/usr/bin/time -f "%e" curl -v -x localhost:9056 http://www.cs.cmu.edu/~prs/bio.html 2>&1)

echo "[*] Sleeping for 5 seconds..."
for i in {1..5}; do
    echo -n "."
    sleep 1
done
echo ""

echo "[*] Sending second request to http://www.cs.cmu.edu/~prs/bio.html..."
cache=$(/usr/bin/time -f "%e" curl -v -x localhost:9056 http://www.cs.cmu.edu/~prs/bio.html 2>&1)

echo "[+] Results ----------------------------------------------- +"
echo ""
echo "    [*] Time Elapsed w/ Fetch: $fetch"
echo "    [*] Time Elapsed w/ Cache: $cache"
echo ""
echo "+ --------------------------------------------------------- +"


