#!/bin/bash

# Test 04: Test the http-proxy with a non-Tufts URL GET request and response

# Start timer for test
echo "+ ------ Test 04: Non-Tufts URL GET request and response ------ +"

echo "[*] Sending initial request to http://neverssl.com..."
fetch=$(time curl -v -x localhost:9056 http://neverssl.com 2>&1)

echo "[*] Sleeping for 5 seconds..."
for i in {1..5}; do
    echo -n "."
    sleep 1
done
echo ""

echo "[*] Sending second request to http://neverssl.com..."
cache=$(time curl -v -x localhost:9056 http://neverssl.com 2>&1)

echo "[+] Results ----------------------------------------------- +"
echo ""
echo "    [*] Time Elapsed w/ Fetch: $fetch"
echo "    [*] Time Elapsed w/ Cache: $cache"
echo ""
echo "+ --------------------------------------------------------- +"
