#!/bin/bash

# Test 01: Test the http-proxy with a simple CONNECT request and response

# Start timer for test
echo "+ ---------- Test 05: Simple CONNECT request and response --------- +"

echo "[*] Sending initial request to http://www.cs.tufts.edu/comp/112/index.html..."
fetch=$(time curl -p -x localhost:9056 http://www.cs.tufts.edu/comp/112/index.html 2>&1)
echo "[*] Sleeping for 5 seconds..."
for i in {1..5}; do
    echo -n "."
    sleep 1
done
echo ""

echo "[*] Sending second request to http://www.cs.tufts.edu/comp/112/index.html..."
cache=$(time curl -p -x localhost:9056 http://www.cs.tufts.edu/comp/112/index.html 2>&1)

echo "[+] Results ----------------------------------------------- +"
echo ""
echo "    [*] Time Elapsed w/ Fetch: $fetch"
echo "    [*] Time Elapsed w/ Cache: $cache"
echo ""
echo "+ --------------------------------------------------------- +"
